export interface Operator{
    id: number;
    razon_social:string;
    nit: number;
    nim_niar: number;
    nro_nim: string;
    fecha_exp_nim: Date;
    tipo_operador: number;
    nro_personeria: string;
    nro_matricula_seprec: string | null;
    fecha_exp_seprec: string | null;
    tipo_doc_creacion: number | null;
    doc_creacion: String | null;
    dl_departamento: number;
    dl_municipio: number;
    dl_direccion: String;
    dl_ubicacion: String;
    correo_inst: String | null;
    tel_fijo: String | null;
    celular: number;
    celular_2: number | null;
    act_exploracion: number | null;
    act_comer_interna: number | null;
    act_comer_externa: number | null;
    act_industrializacion: number | null;
    act_tras_colas: number | null;
    act_explotacion: number | null;
    act_ben_concentracion: number | null;
    act_refinacion: number | null;
    act_fundicion: number | null;
    tipo_explotacion: number | null;
    denominacion_area: String | null;
    nro_codigo_unico: String | null;
    nro_cuadricula: String | null;
    municipio_origen: String | null;
    nro_ruex: String | null;
    verif_cert_liberacion: number | null;
    nro_res_ministerial: number | null;
    nombre_resp_for101: String | null;
    ci_resp_for101: String | null;
    celular_resp_for101: number | null;
    correo_resp_for101: String | null;
    nombre_resp_tmuestra: String | null;
    ci_resp_tmuestra: String | null;
    celular_resp_tmuestra: number | null;
    correo_resp_tmuestra: String | null;
} 